export const UGS_LIST = [
  "120002 - DIRETORIA DE ECON E FINANCAS DA AERONAUTICA",
  "120004 - BASE AEREA DE BRASILIA",
  "120005 - PREFEITURA DE AERONAUTICA DE BRASILIA",
  "120006 - GRUPAMENTO DE APOIO DE BRASILIA",
  "120007 - PREFEITURA DE AERONAUTICA DE RECIFE",
  "120008 - PRIMEIRO CENTRO INT.DEF.AEREA CONTR.TFG.AEREO",
  "120013 - CENTRO DE LANCAMENTO DE ALCANTARA",
  "120016 - GRUPAMENTO DE APOIO DE S J CAMPOS",
  "120019 - HOSPITAL DE AERONAUTICA DE RECIFE",
  "120021 - TERCEIRO CENTRO INT.DEF.AEREA CONTR.TFG.AEREO",
  "120026 - PARQUE MATERIAL AERONAUTICO DE LAGOA SANTA",
  "120030 - BASE AEREA DO GALEAO",
  "120036 - DEPARTAMENTO DE CONTROLE DO ESPACO AEREO",
  "120038 - DIRETORIA DE MATERIAL AERONAUTICO E BELICO",
  "120039 - GRUPAMENTO DE APOIO DO RIO DE JANEIRO",
  "120040 - HOSPITAL CENTRAL AERONAUTICA",
  "120041 - HOSPITAL DE AERONAUTICA DOS AFONSOS",
  "120042 - HOSPITAL DE FORCA AEREA DO GALEAO",
  "120043 - LABORATORIO QUIMICO-FARMACEUTICO DA AERONAUT.",
  "120045 - PREFEITURA DE AERONAUTICA DO GALEAO",
  "120048 - PARQUE DE MAT. DE ELETRONICA DA AERONAUTICA",
  "120049 - PARQUE DE MATERIAL AERONAUTICO DO GALEAO",
  "120053 - PREFEITURA DE AERONAUTICA DOS AFONSOS",
  "120058 - DIRETORIA DE SAUDE",
  "120060 - ACADEMIA DA FORCA AEREA",
  "120064 - ESCOLA DE ESPECIALISTAS DE AERONAUTICA",
  "120066 - HOSPITAL DE FORCA AEREA DE SAO PAULO",
  "120068 - PARQUE DE MATERIAL AERONAUTICO DE SAO PAULO",
  "120015 - CENTRO DE LANÇAMENTO DA BARREIRA DO INFERNO",
  "120071 - CENTRO LOGISTICO DA AERONAUTICA",
  "120072 - SEGUNDO CENTRO INT.DEF.AEREA CONTR.TFG.AEREO",
  "120075 - BASE AEREA DE CANOAS",
  "120077 - HOSPITAL DE AERONAUTICA DE CANOAS",
  "120082 - BASE AEREA DE MANAUS",
  "120087 - BASE AEREA DE BELEM",
  "120089 - HOSPITAL DE AERONAUTICA DE BELEM",
  "120094 - QUARTO CENTRO INT.DEF.AEREA CONTR.TFG.AEREO",
  "120096 - HOSPITAL DE FORCA AEREA DE BRASILIA",
  "120108 - COMISSAO COORD. DO PROGRAMA ANV DE COMBATE",
  "120110 - DEPARTAMENTO DE CIENCIA E TECNOLOGIA AEROESPACIAL",
  "120115 - COMANDO DE OPERAÇÕES AEROESPACIAIS",
  "120127 - COMISSAO DE IMPLANT.DO SIST.DE CONTR.DO E AER",
  "120132 - DIRETORIA DE ENSINO",
  "120133 - DIRETORIA DE ADMINISTRACAO DA AERONAUTICA",
  "120136 - DIRETORIA DE ADMINISTRACAO DO PESSOAL",
  "120140 - INSTITUTO TECNOLOGICO DE AERONAUTICA",
  "120141 - INSTITUTO DE AERONAUTICA E ESPACO",
  "120154 - HOSPITAL DE AERONAUTICA DE MANAUS",
  "120161 - PREFEITURA DE AERONAUTICA DE BELEM",
  "120300 - GRUPO DE TRANSPORTE ESPECIAL",
  "120460 - GRUPO ESPECIAL DE INSPECAO EM VOO",
  "120502 - PREFEITURA DE AERONAUTICA DE PIRASSUNUNGA",
  "120512 - PREFEITURA DE AERONAUT.DE SAO JOSE DOS CAMPOS",
  "120623 - GRUPAMENTO DE APOIO DOS AFONSOS",
  "120624 - BASE AEREA DE ANAPOLIS",
  "120625 - GRUPAMENTO DE APOIO DO DISTRITO FED",
  "120628 - GRUPAMENTO DE APOIO DE BELEM",
  "120629 - GRUPAMENTO DE APOIO DE CANOAS",
  "120630 - GRUPAMENTO DE APOIO DE MANAUS",
  "120631 - BASE AEREA DE NATAL",
  "120632 - GRUPAMENTO DE APOIO DE RECIFE",
  "120633 - GRUPAMENTO DE APOIO DE SAO PAULO",
  "120636 - GRUPAMENTO DE APOIO DE LAGOA SANTA",
  "120637 - BASE AEREA DE BOA VISTA",
  "120638 - BASE AEREA DE CAMPO GRANDE",
  "120641 - BASE AEREA DE PORTO VELHO",
  "120643 - BASE AEREA DE SANTA MARIA",
  "120645 - GRUPAMENTO DE APOIO DO GALEAO",
  "120669 - BASE AEREA DE SANTA CRUZ"
];

export const identifyGroup = (ugName: string): string => {
  const upper = ugName.toUpperCase();
  if (upper.includes("GRUPAMENTO DE APOIO")) return "Grupamentos de Apoio (GAP)";
  if (upper.includes("BASE AEREA")) return "Bases Aéreas (BA)";
  if (upper.includes("HOSPITAL")) return "Hospitais de Aeronáutica e Hospitais de Força Aérea";
  if (upper.includes("PREFEITURA")) return "Prefeituras de Aeronáutica";
  if (upper.includes("PARQUE DE MAT") || upper.includes("PARQUE MAT")) return "Parques de Material";
  if (upper.includes("CINDACTA") || upper.includes("CENTRO INT.DEF.AEREA")) return "CINDACTA";
  if (upper.includes("DIRETORIA") || upper.includes("DEPARTAMENTO") || upper.includes("COMANDO")) return "Órgãos Diretores e Diretorias";
  if (upper.includes("ACADEMIA") || upper.includes("ESCOLA") || upper.includes("ENSINO") || upper.includes("INSTITUTO TECNOLOGICO")) return "Instituições de Ensino";
  if (upper.includes("INSTITUTO DE") || upper.includes("LABORATORIO") || upper.includes("CIENCIA E TECNOLOGIA")) return "Institutos de Ciência e Tecnologia";
  if (upper.includes("CENTRO LOGISTICO") || upper.includes("GRUPO DE TRANSPORTE")) return "Organizações Logísticas";
  if (upper.includes("GRUPO ESPECIAL") || upper.includes("COMISSAO") || upper.includes("CENTRO DE LANCAMENTO")) return "Organizações Operacionais";
  return "Outras Unidades Gestoras";
};

